nabs-app/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resource :passwords
  devise_for :users, :path => 'u', controllers: { confirmations: 'confirmations', sessions: 'sessions' }
  resources :users do
    match "/reset_password", :to => "users#reset_password", :as => "reset_password", via: [:get, :post]
  end
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
      resources :referrals, except: [:show]
      resources :clinics
      resources :specializations
      resources :requests
      get 'scheduled' => 'scheduled#index'
      post 'specializations/condition/create', controller: :specializations, action: :create_condition
      delete 'specializations/condition/delete', controller: :specializations, action: :destroy_condition
      get 'search', as: :doctors, controller: :doctors, action: :search
      post 'select_doctor/:id', as: :select_doctor, controller: :doctors, action: :select_doctor
      get 'referrals/:id/assign_patient', as: :assign_patient, controller: :referrals, action: :assign_patient
      patch 'referrals/:id/send_referral', as: :send_referral, controller: :referrals, action: :send_referral
      patch 'requests/:id/deny', as: :deny_requests, controller: :requests, action: :deny
      patch 'requests/:id/accept', as: :accept_requests, controller: :requests, action: :accept
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

nabs-app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :integer
#  phone_number           :string
#  fax_number             :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :integer
#  invitations_count      :integer          default(0)
#  password_changed       :boolean          default(FALSE)
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  first_name             :string
#  middle_name            :string
#  last_name              :string
#  specialization_id      :integer
#  clinic_id              :integer
#  auto_approve           :boolean          default(FALSE)
#

class User < ApplicationRecord
  enum role: [:staff, :doctor, :admin]
  after_initialize :set_role, :if => :new_record?
  belongs_to :clinic, class_name: "Clinic", foreign_key: :clinic_id
  belongs_to :specialization, class_name: "Specialization", optional: true 
  has_many :requests, foreign_key: :referred_doctor, class_name: 'Referral'
  has_many :referrals, foreign_key: :referring_doctor, class_name: 'Referral'
  has_many :created_referrals, foreign_key: :created_by , class_name: 'Referral'
 # validates_formatting_of :phone_number, using: :us_phone, allow_blank: true
 # validates_formatting_of :fax_number, using: :us_phone, allow_blank: true
 # validates_formatting_of :email, allow_blank: true
  scope :referred, -> {
    joins(:clinic)
      .where(clinics: {role: 'referred'})
  }
  def set_role
    self.role ||= :staff
  end

  def doctor?
    self.role == "doctor"
  end
  
  def staff?
    self.role == "staff"
  end

  def admin?
    self.role == "admin"
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def rollback!
    restore_attributes
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :confirmable, :trackable,
          :validatable
end

nabs-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, :only => [:edit, :show, :update, :destroy]
  before_action :check_admin_auth, :only => [:index, :destroy, :reset_password]
  before_action :check_doctor_auth, :only => [:new, :create]
  before_action :check_current_user, :only => [:show, :edit, :update]

  def index
    @users = User.all
  end

  def new
    if current_user.role == 'admin'
      @roles = [['Admin', 'admin'], ['Doctor', 'doctor'], ['Staff', 'staff']]
      @clinics =
          Clinic.all.map {|c| ["#{c.name} - #{c.address_line1}", c.id]}
    else
      @roles = [['Doctor', 'doctor'], ['Staff', 'staff']]
      @clinics = [["#{current_user.clinic.name} - #{current_user.clinic.address_line1}", current_user.clinic_id]]
    end
    @specs = Specialization.all.map {|s| [s.id, s.title]}
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      User.invite!(email: @user.email) do |u|
        u.skip_invitation = true # Record created but invitation email will not be sent
      end
      redirect_to @user
    else
      flash[:alert] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    @roles = [['Admin', 'admin'], ['Doctor', 'doctor'], ['Staff', 'staff']]
    @clinics =
        Clinic.all
            .map {|c| ["#{c.name} - #{c.address_line1}", c.id]}
    @specs =
        Specialization.all.map {|s| [s.id, s.title]}
  end

  def show
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = "Updated User #{@user.full_name}"
      redirect_to user_path(@user)
    else
      flash[:alert] = @user.errors.full_messages
      redirect_to edit_user_path(params[:id])
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = "Deleted User #{@user.full_name}"
      redirect_to users_path
    else
      flash[:alert] = @user.errors.full_messages
      redirect_to users_path
    end
  end

  def reset_password
    @user = User.find(params[:user_id])
    @user.confirmed_at = nil
    @user.password_changed = false
    if @user.save
      @user.send_confirmation_instructions
      redirect_to @user #Change this
    else
      flash[:alert] = @user.errors.full_messages
      redirect_to users_path #Change this
    end

  end

  private
  def check_current_user
    unless current_user.admin? or current_user == @user
      redirect_to unauthenticated_root_url, alert: "You do not have permission to view that page"
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def same_clinic
    not (current_user.clinic.nil? or @user.clinic.nil?) and current_user.clinic == @user.clinic
  end

  def user_params
    if current_user.admin? || current_user.doctor?
      params.require(:user).
          permit(
              :role,
              :first_name,
              :last_name,
              :middle_name,
              :clinic_id,
              :fax_number,
              :phone_number,
              :email,
              :password,
              :password_confirmation,
              :invitation_token,
              :specialization_id,
              :auto_approve
          ).delete_if do |key, val|
        key == 'role' and val == "admin" and not current_user.admin?
      end
    elsif @user == current_user
      params.require(:user).
          permit(
              :first_name,
              :last_name,
              :middle_name,
              :clinic_id,
              :fax_number,
              :phone_number,
              :email,
              :password,
              :password_confirmation,
              :invitation_token,
              :specialization_id
          )
    end
  end
end

nabs-app/app/helpers/users_helper.rb
module UsersHelper
end

nabs-app/app/views/users/_form.html.erb
<h2 class="ui  dividing header">Account</h2>

<div class="ui grid container">
    <div class="two wide column"></div>

    <div class="twelve wide column">

        <%= form_for @user, html: { class: 'ui huge form' } do |f| %>
            <% if current_user == @user %>
            <h2 class="ui  dividing header">Password</h2>
            <%= link_to 'Reset Password', edit_passwords_path, class: 'ui button red fluid big' %>

            <% elsif not @user.id.nil? and current_user.admin? %>
            <h2 class="ui  dividing header">Password</h2>
            <%= link_to 'Reset Password', user_reset_password_path(@user), class: 'ui button red fluid big' %>
            <% end %>

        <h2 class="ui dividing header">Role</h2>
        <div class="field">
            <div class="ui search selection fluid dropdown">
                <%= f.hidden_field :role %>
                <i class="dropdown icon"></i>
                <div class="default text"></div>
                <div class="menu">
                    <% @roles.each do |s| %>
                        <% if s != 'admin' %>
                        <div class="item" data-value="<%= s[1] %>" data-text="<%= s[0] %>"><%= s[0] %></div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>

        <h2 class="ui dividing header">Name</h2>
        <div class="equal width fields">
            <div class="field">
                <label>First Name</label>
                <%= f.text_field :first_name %>
            </div>
            <div class="field">
                <label>Last Name</label>
                <%= f.text_field :last_name %>
            </div>
            <div class="field">
                <label>Middle Name</label>
                <%= f.text_field :middle_name %>
            </div>
        </div>

        <h2 class="ui dividing header">Contact</h2>
        <div class="equal width fields">
            <div class="field">
                <label>Email</label>
                <%= f.email_field :email, placeholder: "example@gmail.com" %>
            </div>
            <div class="field">
                <label>Phone #</label>
                <%= f.phone_field :phone_number, placeholder: "(###)###-####" %>
            </div>
            <div class="field">
                <label>Fax #</label>
                <%= f.phone_field :fax_number, placeholder: "(###)###-####" %>
            </div>
        </div>

        <% if current_user.role != 'admin' || @user.role != 'admin' %>
        <h2 class="ui dividing header">Clinic</h2>
        <div class="field">
            <div class="ui search selection fluid dropdown">
                <%= f.hidden_field :clinic_id %>
                <i class="dropdown icon"></i>
                <div class="default text"></div>
                <div class="menu">
                    <% @clinics.each do |s| %>
                    <div class="item" data-value="<%= s[1] %>" data-text="<%= s[0] %>"><%= s[0] %></div>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>

        <% if current_user.admin? || current_user.role == 'doctor' %>
        <h2 class="ui dividing header">Specialization</h2>
        <div class="field">
            <div class="ui search selection fluid dropdown">
                <%= f.hidden_field :specialization_id %>
                <i class="dropdown icon"></i>
                <div class="default text"></div>
                <div class="menu">
                    <% @specs.each do |s| %>
                    <div class="item" data-value="<%= s[0] %>" data-text="<%= s[1] %>"><%= s[1] %></div>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>

        <% if current_user.role == 'doctor' && @user.clinic.referred? %>
        <div class="field">
            <div class="ui checkbox">
                <%= f.check_box :auto_approve %>
                <label>Auto Approve Referrals?</label>
            </div>
        </div>
        <% end %>

        <button class="ui red button big" type="submit">Save</button>
    <% end %>
    </div>
</div>

nabs-app/app/views/users/edit.html.erb
<!--
<h2 class="ui  dividing header">Edit Account</h2>

<div class="ui grid container">
-->
<%= render "form_header/form_header"%>
<%= render "users/form" %>

nabs-app/app/views/users/index.html.erb
<h2 class="ui  dividing header">Contact</h2>
<%= link_to 'New User', new_user_path, class:'button ui medium blue'  %>

<table class="table ui striped tablet stackable celled">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Clinic</th>
            <th>Role</th>
            <th>Specialization</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Fax</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.full_name %></td>
            <td><%= user.clinic.try(:name)%></td>
            <td><%= user.role.capitalize %></td>
            <td><%= user.specialization.try(:title) if user.doctor? %></td>
            <td><%= user.email %></td>
            <td><%= user.phone_number %></td>
            <td><%= user.fax_number %></td>
            <td><%= link_to('Edit', edit_user_path(user), class:'button ui yellow')%></td>
            
            <% unless current_user == user %>
            <td><%= link_to('Delete', user, method: :delete, data: { confirm: "Are you sure?" }, class: 'button ui red')  %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

nabs-app/app/views/users/new.html.erb
<%= render "form_header/form_header"%>
<%= render "users/form" %>

nabs-app/app/views/users/show.html.erb
<h2 class="ui  dividing header">Account</h2>

<table class="ui large striped celled table">
  <tbody>

  <tr>
    <td class="center aligned">First Name</td>
    <td><%= @user.first_name %></td>
  </tr>
  <tr>
    <td class="center aligned">Middle Name</td>
    <td><%= @user.middle_name %></td>
  </tr>
  <tr>
    <td class="center aligned">Last Name</td>
    <td><%= @user.last_name %></td>
  </tr>

  <tr>
    <td class="center aligned">Role</td>
    <td><%= @user.role %></td>
  </tr>
  <tr>
    <td class="center aligned">Email</td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td class="center aligned">Phone #</td>
    <td><%= @user.phone_number %></td>
  </tr>
  <tr>
    <td class="center aligned">Fax #</td>
    <td><%= @user.fax_number %></td>
  </tr>
  <% if not current_user.role == 'admin' %>
    <tr>
      <td class="center aligned">Clinic</td>
      <td><%= @user.clinic.try(:name) %></td>
    </tr>
  <% end %>

  <% if current_user.role == 'doctor' %>
    <tr>
      <td class="center aligned">Specialization</td>
      <td><%= @user.specialization.try(:title) %></td>
    </tr>
    <% if @user.clinic.referred? %>
      <tr>
        <td class="center aligned">Auto Approve Referrals?</td>
        <td><%= @user.auto_approve ? 'Yes' : 'No' %></td>
      </tr>
    <% end %>
  <% end %>
  <tr>
    <td colspan="2" class="center aligned"><%= link_to('Edit', edit_user_path, class: 'button ui big yellow') %></td>
  </tr>

  </tbody>
</table>