nabs-app/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resource :passwords
  devise_for :users, :path => 'u', controllers: { confirmations: 'confirmations', sessions: 'sessions' }
  resources :users do
    match "/reset_password", :to => "users#reset_password", :as => "reset_password", via: [:get, :post]
  end
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
      resources :referrals, except: [:show]
      resources :clinics
      resources :specializations
      resources :requests
      get 'scheduled' => 'scheduled#index'
      post 'specializations/condition/create', controller: :specializations, action: :create_condition
      delete 'specializations/condition/delete', controller: :specializations, action: :destroy_condition
      get 'search', as: :doctors, controller: :doctors, action: :search
      post 'select_doctor/:id', as: :select_doctor, controller: :doctors, action: :select_doctor
      get 'referrals/:id/assign_patient', as: :assign_patient, controller: :referrals, action: :assign_patient
      patch 'referrals/:id/send_referral', as: :send_referral, controller: :referrals, action: :send_referral
      patch 'requests/:id/deny', as: :deny_requests, controller: :requests, action: :deny
      patch 'requests/:id/accept', as: :accept_requests, controller: :requests, action: :accept
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

nabs-app/app/views/layouts/_admin.html.erb
<a class="item <%= current_page?(users_path) ? "active" : nil %>" href= <%= users_path %>>
    <i class="large user icon"></i>Users
</a>

<a class="item <%= current_page?(clinics_path) ? "active" : nil %>" href= <%= clinics_path %>>
    <i class="ui icon home large"></i>Clinics
</a>

<a class="item <%= current_page?(specializations_path) ? "active" : nil %>" href= <%= specializations_path %>>
  <i class="ui hospital icon large"></i>Specializations
</a>

<a class="item <%= current_page?(user_path(current_user)) ? "active" : nil %>" href= <%= user_path(current_user) %>>
    <i class="large user icon"></i>Account
</a>

nabs-app/app/views/layouts/_flashes.html.erb
<% flash.each do |key, msg| %>
    
    <% if flash[:alert] %>
    <div class="ui icon message red">
        <i class="exclamation icon large"></i>
        <div class="content">
            <div class="header">
                Alert
            </div>
            <%= flash[:alert] %>
        </div>
    </div>
    
    <% elsif flash[:message] %>
    <div class="ui icon message blue">
        <i class="exclamation icon large"></i>
        <div class="content">
            <div class="header">
                Message
            </div>
            <%= flash[:message] %>
        </div>
    </div>
    
    <% elsif flash[:notice] %>
    <div class="ui icon message green">
        <i class="exclamation icon large"></i>
        <div class="content">
            <div class="header">
                Notice
            </div>
            <%= flash[:notice] %>
        </div>
    </div>
    
    <% end %>
<% end %>

nabs-app/app/views/layouts/_header.html.erb
<div class="ui six item stackable borderless labeled icon menu">
    <div class="ui container">
        <a href="<%= current_user ? home_index_path : new_user_session_path %>" class="fitted item">
            <img class="ui medium image left" src=<%= asset_path 'OSU-WexMedCtr-4C-StackedK-CMYK.jpg' %> alt="OSUMedicalCenterLogo">
        </a>
        
        <div class="right menu">
            <% if current_user && current_user.role == 'admin' %>
                <%= render 'layouts/admin' %>
            <% elsif current_user && current_user.clinic.try(:referrer?) && current_user.role == 'staff' %>
                <%= render 'layouts/staff' %>
            <% elsif current_user && current_user.clinic.try(:referrer?) %>
                <%= render 'layouts/referring' %>
            <% elsif current_user && current_user.clinic.try(:referred?) %>
                <%= render 'layouts/referred' %>
            <% end %>
            
            <%= render 'devise/menu/login_items' %>
        </div>
    </div>
</div>

nabs-app/app/views/layouts/_referred.html.erb
<a class="item <%= current_page?(requests_path) ? "active" : nil %>" href= <%= requests_path %>>
    <i class="calendar outline icon"></i>Requests
</a>

<a class="item <%= current_page?(scheduled_path) ? "active" : nil %>" href= <%= scheduled_path %>>
  <i class="calendar check icon"></i>Scheduled
</a>

<a class="item <%= current_page?(user_path(current_user)) ? "active" : nil %>" href= <%= user_path(current_user) %>>
    <i class="large user icon"></i>Account
</a>

nabs-app/app/views/layouts/_referring.html.erb
<a class="item <%= current_page?(doctors_path) ? "active" : nil %>" href= <%= doctors_path %>>
    <i class="ui icon search large"></i>Doctors
</a>

<a class="item <%= current_page?(new_referral_path) ? "active" : nil %>" href= <%= new_referral_path %>>
    <i class="ui icon plus large"></i>Create
</a>

<a class="item <%= current_page?(referrals_path) ? "active" : nil %>" href= <%= referrals_path %>>
    <i class="ui icon edit large"></i>Pending
</a>

<a class="item <%= current_page?(user_path(current_user)) ? "active" : nil %>" href= <%= user_path(current_user) %>>
    <i class="large user icon"></i>Account
</a>

nabs-app/app/views/layouts/_staff.html.erb
<a class="item <%= current_page?(doctors_path) ? "active" : nil %>" href= <%= doctors_path %>>
    <i class="ui icon search large"></i>Doctors
</a>

<a class="item <%= current_page?(new_referral_path) ? "active" : nil %>" href= <%= new_referral_path %>>
    <i class="ui icon plus large"></i>Create
</a>

<a class="item <%= current_page?(referrals_path) ? "active" : nil %>" href= <%= referrals_path %>>
    <i class="ui icon edit large"></i>Pending
</a>

<a class="item <%= current_page?(user_path(current_user)) ? "active" : nil %>" href= <%= user_path(current_user) %>>
    <i class="large user icon"></i>Account
</a>

nabs-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>NabsApp</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="ui container center aligned">
            <%= render 'layouts/header' %>
            <br/>
            
            <%= render 'layouts/flashes' %>
            <hr>
            <%= yield %>
        </div>
    </body>
</html>