nabs-app/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resource :passwords
  devise_for :users, :path => 'u', controllers: { confirmations: 'confirmations', sessions: 'sessions' }
  resources :users do
    match "/reset_password", :to => "users#reset_password", :as => "reset_password", via: [:get, :post]
  end
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
      resources :referrals, except: [:show]
      resources :clinics
      resources :specializations
      resources :requests
      get 'scheduled' => 'scheduled#index'
      post 'specializations/condition/create', controller: :specializations, action: :create_condition
      delete 'specializations/condition/delete', controller: :specializations, action: :destroy_condition
      get 'search', as: :doctors, controller: :doctors, action: :search
      post 'select_doctor/:id', as: :select_doctor, controller: :doctors, action: :select_doctor
      get 'referrals/:id/assign_patient', as: :assign_patient, controller: :referrals, action: :assign_patient
      patch 'referrals/:id/send_referral', as: :send_referral, controller: :referrals, action: :send_referral
      patch 'requests/:id/deny', as: :deny_requests, controller: :requests, action: :deny
      patch 'requests/:id/accept', as: :accept_requests, controller: :requests, action: :accept
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

nabs-app/app/models/specialization.rb
# == Schema Information
#
# Table name: specializations
#
#  id    :integer          not null, primary key
#  title :string
#

class Specialization < ApplicationRecord
  has_many :users, through: :specializes
  has_many :conditions
  has_many :referrals
end

nabs-app/app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  before_action :check_admin_auth

  def index
    @specializations = Specialization.all
    @specialization = Specialization.new
    @conditions = Condition.all
    @condition = Condition.new
  end

  def show
    @specialization = Specialization.find(params[:id])
  end

  def new
    @specialization = Specialization.new
  end

  def create
    @specialization = Specialization.new(specialization_params)
    if @specialization.save
      flash[:notice] = "Created Specialization #{@specialization.title}"
    else
      flash[:alert] = @specialization.errors.full_messages
    end
    redirect_to specializations_path
  end

  def create_condition
    @condition = Condition.new(condition_params)
    if @condition.save
      flash[:notice] = "Created Condition #{@condition.name}"
    else
      flash[:alert] = @condition.errors.full_messages
    end
    redirect_to specializations_path
  end

  def edit
    @specialization = Specialization.find(params[:id])
  end

  def update
    @specialization = Specialization.find(params[:id])
    if @specialization.update_attributes(specialization_params)
      flash[:notice] = "Updated Specialization #{@specialization.name}"
      redirect_to specializations_path
    else
      flash[:alert] = @specialization.errors.full_messages
      redirect_to edit_specialization_path(params[:id])
    end
  end

  # New version of destroy
  def destroy
    begin
      @specialization = Specialization.try(:find, params[:id])
      flash[:notice] = 'Deleted Specialization'
      @result = @specialization.destroy
      # if destroy doesn't work, throw the error message
      flash[:alert] = @specialization.errors.full_messages unless @result
    rescue => e
      flash[:alert] = "Unknown Error trying to delete specialization #{params[:id]}, Errors: #{e}"
    ensure
      # always redirect back to specializations page
      redirect_to '/specializations/'
    end
  end

  def destroy_condition
    begin
      @condition = Condition.find(params[:id])
      flash[:notice] = 'Deleted Condition'
      @result = @condition.destroy
      # if destroy doesn't work, throw the error message
      flash[:alert] = @condition.errors.full_messages unless @result
    rescue => e
      flash[:alert] = "Unknown Error trying to delete condition #{params[:id]}, Errors: #{e}"
    ensure
      # always redirect back to specializations page
      redirect_to '/specializations/'
    end
  end

  private

  def specialization_params
    params.require(:specialization)
          .permit(:title)
  end

  def condition_params
    params.require(:condition)
          .permit(:name, :specialization_id)
  end
end

nabs-app/app/views/specializations/index.html.erb
<h2 class="ui  dividing header">Specialization List</h2>

<table class="table ui striped tablet stackable celled">
  <thead>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Conditions</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @specializations.each do |s| %>
    <tr>
      <td><%= s.id %></td>
      <td><%= s.title %></td>
      <td>
        <table class="ui two column table">
          <tbody>
            <% @conditions.select{|cond| cond.specialization_id == s.id}.each do |c| %>
              <tr>
                <td class="left aligned"><%= c.name %></td>
                <td class="right aligned">
                  <%= link_to('Delete', specializations_condition_delete_path(id: c.id), method: 'delete', class: 'button mini ui red') %>
                </td>
              </tr>
            <% end %>
            <%= form_for(@condition, url: specializations_condition_create_path, html: { class: 'ui small form' }) do |f| %>
              <%= f.text_field :name, placeholder: "New Condition Name" %>
              <%= f.hidden_field(:specialization_id, {value: s.id}) %>
              <%= f.submit 'Save', class: "ui button small blue" %>
            <% end %>
          </tbody>
        </table>
      </td>
      <td class="center aligned"><%= link_to('Delete', s, method: :delete, class: 'button ui red') %></td>
    </tr>
  <% end %>
  <div>
    <%= form_for(@specialization, controller: :specializations, html: { class: 'ui small form' }) do |f| %>
      <%= f.text_field :title, placeholder: "New Specialization Title" %>
      <%= f.submit 'Save', class: "ui button small blue" %>
    <% end %>
  </div>
  </tbody>
</table>