nabs-app/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resource :passwords
  devise_for :users, :path => 'u', controllers: { confirmations: 'confirmations', sessions: 'sessions' }
  resources :users do
    match "/reset_password", :to => "users#reset_password", :as => "reset_password", via: [:get, :post]
  end
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
      resources :referrals, except: [:show]
      resources :clinics
      resources :specializations
      resources :requests
      get 'scheduled' => 'scheduled#index'
      post 'specializations/condition/create', controller: :specializations, action: :create_condition
      delete 'specializations/condition/delete', controller: :specializations, action: :destroy_condition
      get 'search', as: :doctors, controller: :doctors, action: :search
      post 'select_doctor/:id', as: :select_doctor, controller: :doctors, action: :select_doctor
      get 'referrals/:id/assign_patient', as: :assign_patient, controller: :referrals, action: :assign_patient
      patch 'referrals/:id/send_referral', as: :send_referral, controller: :referrals, action: :send_referral
      patch 'requests/:id/deny', as: :deny_requests, controller: :requests, action: :deny
      patch 'requests/:id/accept', as: :accept_requests, controller: :requests, action: :accept
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

nabs-app/app/models/referral.rb
# == Schema Information
#
# Table name: referrals
#
#  id                  :integer          not null, primary key
#  status              :integer
#  date                :date
#  created_by_id       :integer
#  patient_id          :integer
#  referring_doctor_id :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  referred_doctor_id  :integer
#  sent_at             :datetime
#  urgent              :boolean          default(FALSE)
#  next_available      :boolean          default(FALSE)
#  monday              :boolean          default(FALSE)
#  tuesday             :boolean          default(FALSE)
#  wednesday           :boolean          default(FALSE)
#  thursday            :boolean          default(FALSE)
#  friday              :boolean          default(FALSE)
#  saturday            :boolean          default(FALSE)
#  sunday              :boolean          default(FALSE)
#  specialization_id   :integer
#

class Referral < ApplicationRecord
  belongs_to :patient, class_name: 'Patient', optional: true
  belongs_to :created_by, class_name: 'User', foreign_key: :created_by_id
  belongs_to :referring_doctor, class_name: 'User', foreign_key: :referring_doctor_id, optional: true
  belongs_to :referred_doctor, class_name: 'User', foreign_key: :referred_doctor_id, optional: true
  belongs_to :specialization, class_name: 'Specialization', foreign_key: 'specialization_id', optional: true
  scope :from_clinic, ->(c) {
    joins(:created_by).
    where(users: {clinic_id: c.id})
  }
end

nabs-app/app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  before_action :check_referring_clinic_auth

  def send_referral
    @referral = @referrals.find(params[:id])
    if @referral
      @patient = @referral.patient
      if @patient.update_attributes(patient_params)
        if @referral.update_attributes(status: @referral.referred_doctor.auto_approve? ? 3 : 2)
          flash[:notice] =  "Referral Sent"
          PatientMailer.send_accept_message(@referral).deliver_now! if @referral.status == 3
          redirect_to home_index_path
        else
          flash[:alert] =  @referral.errors.full_messages
          redirect_to assign_patient_path(patient_params)
        end
      else
        flash[:alert] =  @patient.errors.full_messages
        redirect_to assign_patient_path(patient_params)
      end
    else
      flash[:alert] =  "Referral does not belong to your office"
      redirect_to referrals_path
    end
  end

  before_action :clinic_check

  def index
    @statuses = ['new', 'edited', 'sent', 'accepted','denied']
  end

  def new
    @referral = Referral.new

    @referring_doctors =
      User
      .where(role: :doctor, clinic_id: current_user.clinic_id)
      .map{|u| [u.full_name, u.id]}
    @referred_doctors =
      User
      .where(role: :doctor)
      .where.not(clinic_id: current_user.clinic_id)
      .map{|u| [u.full_name, u.id]}

    @specialties =
      Specialization.all
      .map{|s| [s.title, s.id]}
  end

  def create
    @referral = Referral.new(referral_params)

    @referring_doctors =
      User
      .where(role: :doctor, clinic_id: current_user.clinic_id)
      .map{|u| [u.full_name, u.id]}

    @specialties =
      Specialization.all
      .map{|s| [s.title, s.id]}

    @referral.created_by = current_user
    @referral.patient = Patient.create!
    @referral.status = 0
    if @referral.save
      flash[:notice] = "Referral Created"
      redirect_to assign_patient_path(@referral.patient_id)
    else
      flash[:alert] =  @referral.errors.full_messages
      redirect_to new_referral_path(referral_params)
    end
  end

  def edit
    @referral = @referrals.find(params[:id])
    @specialties =
      Specialization.all
      .map{|s| [s.title, s.id]}
  end

  def update
    @referral = @referrals.find(params[:id])
    @referral.patient = Patient.create! unless @referral.patient
    if @referral.update_attributes(referral_params)
      @referral.update_attribute(:status, 1)
      flash[:notice] = "Referral Updated"
      redirect_to assign_patient_path(@referral.patient_id)
    else
      flash[:alert] =  @referral.errors.full_messages
      redirect_to edit_referral_path(params[:id])
    end
  end

  def destroy
    @referral = @referrals.find(params[:id])
    if @referral.destroy
      flash[:alert] =   "Deleted Referral #{@referral.id}"
      redirect_to referrals_path
    else
      flash[:alert] =  @referral.errors.full_messages
      redirect_to referrals_path
    end
  end

  def assign_patient
    @patient = Patient.find(params[:id])
    unless @referrals.include?(@patient.referral)
      flash[:alert] =  "Patient does not belong to a referral generated by your office"
      redirect_to referrals_path
    else
      @sexes = [['Female','F'],['Male','M'],['Unknown','U']]
    end
  end

  private
  def referral_params
    params
      .require(:referral)
      .permit(
        :urgent,
        :next_available,
        :specialization_id,
        :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday,
        :referring_doctor_id,
        :referred_doctor_id
      )
  end
  def patient_params
    params
      .require(:patient)
      .permit(
        :ssn,
        :first_name,
        :middle_name,
        :last_name,
        :birth_date, :sex,
        :fax_number, :phone_number, :email,
        :insurance, :plan_group_no,
        :address_line1, :address_line2, :city, :state, :zip_code
      )
  end

  def clinic_check
    # matches clinic of creator of referral
    #reject those that have not been sent
    # nil default, 1 pending, 2 sent, 3 accept, 4 denied
    @referred_doctors = User.referred.map{|d| [d.full_name, d.id]}
    @referring_doctors = Clinic.find(current_user.clinic_id).referring_doctors
    @referrals = Referral.from_clinic(current_user.clinic).where(status: [nil,0,1])
  end
end

nabs-app/app/helpers/referral_helper.rb
module ReferralHelper
end

nabs-app/app/views/referrals/_form.erb
<h2 class="ui dividing header">Referral</h2>
<div class="ui grid container">
    <div class="two wide column"></div>
    
    <div class="twelve wide column">
        <%= form_for(@referral, html: {class: "ui large form"}) do |f| %>
            <h2 class="ui  dividing header"><i class="ui icon exclamation large"></i>Status</h2>
            <div class="fields">
                <div class="field">
                    <div class="ui checkbox">
                        <%= f.check_box :urgent %>
                        <label>Urgent?</label>
                    </div>
                </div>
                
                <div class="field">
                    <div class="ui checkbox">
                        <%= f.check_box :next_available %>
                        <label>Next Available Appt?</label>
                    </div>
                </div>
            </div>
            <h2 class="ui  dividing header"><i class="ui icon calendar large"></i>Preferred Day</h2>
            <div class="equal width fields">
                <div class="field">
                    <div class="ui horizontal celled relaxed list">
                        <div class="item">
                            <div class="ui large checkbox">
                                <%= f.check_box :monday %>
                                <label>Monday</label>
                            </div>
                        </div>
                        <div class="item">
                            <div class="ui large checkbox">
                                <%= f.check_box :tuesday %>
                                <label>Tuesday</label>
                            </div>
                        </div>
                        <div class="item">
                            <div class="ui large checkbox">
                                <%= f.check_box :wednesday %>
                                <label>Wednesday</label>
                            </div>
                        </div>
                        <div class="item">
                            <div class="ui large checkbox">
                                <%= f.check_box :thursday %>
                                <label>Thursday</label>
                            </div>
                        </div>
                        <div class="item">
                            <div class="ui large checkbox">
                                <%= f.check_box :friday %>
                                <label>Friday</label>
                            </div>
                        </div>
                        <div class="item">
                            <div class="ui large checkbox">
                                <%= f.check_box :saturday %>
                                <label>Saturday</label>
                            </div>
                        </div>
                        <div class="item">
                            <div class="ui large checkbox">
                                <%= f.check_box :sunday %>
                                <label>Sunday</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <h2 class="ui  dividing header"><i class="ui icon pencil large"></i>Diagnosis</h2>
            <div class="equal width fields">
                <div class="field">
                    <label>Specialty</label>
                    <div class="ui search selection fluid dropdown">
                        <%= f.hidden_field :specialization_id %>
                        <i class="dropdown icon"></i>
                        <div class="default text"></div>
                        <div class="menu">
                            <% @specialties.each do |s| %>
                                <div class="item" data-value="<%= s[1] %>" data-text="<%= s[0] %>"><%= s[0] %></div>
                            <% end %>
                        </div>
                    </div>
                </div>
                <!--
      <div class="field">
        <label>Diagnostic Details</label>
        <%- # f.text_area :description, placeholder:"Relevant diagnostic details...", rows:"4", cols:"50" %>
      </div>
-->
            </div>
            <h2 class="ui dividing header"><i class="ui icon doctor large"></i>Doctors</h2>
            <div class="equal width fields">
                <div class="field">
                    <label>Referring Physician</label>
                    <div class="ui search selection fluid dropdown">
                        <% if current_user.role != 'doctor' %>
                            <%= f.hidden_field :referring_doctor_id %>
                            <i class="dropdown icon"></i>
                            <div class="default text"></div>
                            <div class="menu">
                                <% @referring_doctors.each do |s| %>
                                    <div class="item" data-value="<%= s[1] %>" data-text="<%= s[0] %>"><%= s[0] %></div>
                                <% end %>
                            </div>
                        <% else %>
                            <%= f.hidden_field :referring_doctor_id, value: current_user.id %>
                            <div class="default text"><%= current_user.full_name %></div>
                        <% end %>
                    </div>
                </div>
                <div class="field">
                    <label>Referred Physician</label>
                    <div class="ui search selection fluid dropdown">
                        <%= f.hidden_field :referred_doctor_id %>
                        <i class="dropdown icon"></i>
                        <div class="default text"></div>
                        <div class="menu">
                            <% @referred_doctors.each do |s| %>
                                <div class="item" data-value="<%= s[1] %>" data-text="<%= s[0] %>"><%= s[0] %></div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <%= f.submit 'Save and Continue', class: 'button ui medium blue' %>
        <% end %>
    </div>
    <div class="two wide column"></div>
</div>

nabs-app/app/views/referrals/_patient_form.erb
<style>
    .form_image {
      width: 15px;
      height: 15px;
      max-height: 20px;
      max-width: 20px;
    }

    .form_image img {
      width: 100%;
      height: 100%;
    }

    body {
      background-color: lightgray;
    }

    .ui {
      background-color: lightgray;
    }

</style>

<a class="form_image">
  <img src=<%= asset_path 'form_image2.jpg' %>>
</a>
<%= form_for @patient, url: send_referral_path(@patient.referral.id), html: {class: "ui huge form"} do |f| %>
    <h2 class="ui  dividing header">Patient</h2>

    <div class="equal width fields">
        <div class="field">
            <label>First Name</label>
            <%= f.text_field "first_name", placeholder:"First Name" %>
        </div>

        <div class="field">
            <label>Middle Initial</label>
            <%= f.text_field "middle_name", placeholder:"Middle Name" %>
        </div>

        <div class="field">
            <label>Last Name</label>
            <%= f.text_field "last_name", placeholder: "Last Name" %>
        </div>
    </div>

    <div class="equal width fields">
        <div class="field">
            <label>Sex</label>
            <div class="ui search selection fluid dropdown">
                <%= f.hidden_field :state %>
                <i class="dropdown icon"></i>
                <div class="default text"></div>

                <div class="menu">
                    <% @sexes.each do |s| %>
                    <div class="item" data-value="<%=s[1]%>" data-text="<%=s[0]%>"><%=s[0]%></div>
                    <% end %>
                </div>
            </div>
        </div>

        <div class="field">
            <label>DOB</label>
            <%= f.text_field :birth_date %>
        </div>

        <div class="field">
            <label>SSN</label>
            <%= f.text_field :ssn, placeholder:"XXX-XX-XXXX" %>
        </div>
    </div>

    <h2 class="ui  dividing header">Insurance</h2>
    <div class="equal width fields">
        <div class="field">
            <label>Insurance</label>
            <%= f.text_field :insurance %>
        </div>

        <div class="field">
            <label>Group/Plan #</label>
            <%= f.text_field :plan_group_no %>
        </div>
    </div>

    <h2 class="ui  dividing header">Location</h2>
    <div class="equal width fields">
        <div class="field">
            <label>Address Line 1</label>
            <%= f.text_field :address_line1, placeholder:"Street Address, P.O. box, Company Name, c/o" %>
        </div>

        <div class="field">
            <label>Address Line 2</label>
            <%= f.text_field :address_line2, placeholder:"Apartment, Suite, Unit, Building, Floor, Etc." %>
        </div>
    </div>

    <div class="equal width fields">
        <div class="field">
            <label>City</label>
            <%= f.text_field :city %>
        </div>

        <div class="field">
            <label>State</label>
            <div class="ui search selection fluid dropdown">
                <%= f.hidden_field :state %>
                <i class="dropdown icon"></i>
                <div class="default text"></div>
                <div class="menu">
                    <% us_states.each do |s| %>
                    <div class="item" data-value="<%=s[1]%>" data-text="<%=s[0]%>"><%=s[0]%></div>
                    <% end %>
                </div>
            </div>
         </div>

        <div class="field">
            <label>Zip Code</label>
            <%= f.text_field :zip_code %>
        </div>
    </div>

    <h2 class="ui dividing header">Contact</h2>
    <div class="equal width fields">
        <div class="field">
            <label>Email</label>
            <%= f.email_field :email, placeholder:"email@sample.com" %>
        </div>

        <div class="field">
            <label>Phone #</label>
            <%= f.phone_field :phone_number, placeholder:"(###)###-####" %>
        </div>

        <div class="field">
            <label>Fax #</label>
            <%= f.phone_field :fax_number, placeholder:"(###)###-####" %>
        </div>
    </div>

    <%= f.submit 'Send Referral', class:'button ui large blue' %>
<% end %>

nabs-app/app/views/referrals/assign_patient.html.erb
<!--
-<h2 class="ui dividing header">Patient Information</h2>
-->
<%= render 'patient_form' %>

nabs-app/app/views/referrals/edit.html.erb
<!--
<h2 class="ui dividing header">Edit Referral</h2>
-->
<%= render "form_header/form_header"%>
<%= render 'form' %>

nabs-app/app/views/referrals/index.html.erb
<h2 class="ui dividing header">Referrals</h2>

<table class="table ui striped tablet stackable celled">
    <thead>
        <tr>
            <th>Status</th>
            <th>Specialty/Diagnosis</th>
            <th>Referring Doctor</th>
            <th>Referred Doctor</th>
            <th>Creator</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <% @referrals.each do |r| %>
        <tr>
            <td><%= @statuses[r.status || 0] %></td>
            <td><%= r.specialization.try(:title) %></td>
            <td><%= r.referring_doctor.try(:full_name) %></td>
            <td><%= r.referred_doctor.try(:full_name) %></td>
            <td><%= r.created_by.try(:full_name) %></td>
            <td><%= r.created_at%></td>
            <td><%= distance_of_time_in_words_to_now(r.updated_at) %></td>
            <td><%= link_to 'Edit', edit_referral_path(id: r.id), class: 'button ui yellow' %></td>
            <td><%= button_to "Delete", referral_path(id: r.id), method: :delete, class: 'ui button red' %></td>
        </tr>
        <% end %>
    </tbody>
</table>

nabs-app/app/views/referrals/new.html.erb
<!--
<h2 class="ui dividing header">Create Referral</h2>
-->
<%= render "form_header/form_header"%>
<%= render 'form' %>